# Generated by Django 5.2.7 on 2025-10-14 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(default='USA', max_length=100, verbose_name='Country')),
                ('position_applied', models.CharField(max_length=200, verbose_name='Position Applied For')),
                ('current_company', models.CharField(blank=True, max_length=200, verbose_name='Current Company')),
                ('current_position', models.CharField(blank=True, max_length=200, verbose_name='Current Position')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('highest_education', models.CharField(blank=True, choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=100, verbose_name='Highest Education Level')),
                ('field_of_study', models.CharField(blank=True, max_length=200, verbose_name='Field of Study')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profile')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio/Website')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume/CV')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Cover Letter')),
                ('skills', models.TextField(blank=True, help_text='e.g., Python, Django, JavaScript', verbose_name='Skills (comma-separated)')),
                ('certifications', models.TextField(blank=True, verbose_name='Certifications')),
                ('available_start_date', models.DateField(blank=True, null=True, verbose_name='Available Start Date')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Annual salary expectation', max_digits=10, null=True, verbose_name='Expected Salary')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Application Status')),
                ('applied_date', models.DateTimeField(auto_now_add=True, verbose_name='Application Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('notes', models.TextField(blank=True, help_text='For employer use only', verbose_name='Internal Notes')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-applied_date'],
            },
        ),
    ]
