# Generated by Django 5.2.7 on 2025-10-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='access_code',
            field=models.CharField(blank=True, help_text='Code for candidate to check application status', max_length=8, null=True, unique=True, verbose_name='Access Code'),
        ),
    ]
