# Generated by Django 5.2.7 on 2025-10-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='portfolio_url',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('elementary', 'Ensino Fundamental'), ('high_school', 'Ensino Médio'), ('associate', 'Tecnólogo'), ('bachelor', 'Bacharelado'), ('other', 'Outro')], max_length=100, verbose_name='Highest Education Level'),
        ),
    ]
