# Generated by Django 5.2.7 on 2025-10-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_remove_candidate_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: xxx.xxx.xxx-xx', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nome Completo'),
        ),
    ]
