# Generated by Django 5.2.7 on 2025-10-16 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_remove_candidate_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: xxx.xxx.xxx-xx', max_length=14, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: xxx.xxx.xxx-xx', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('analfabeto', 'Analfabeto'), ('fundamental_incompleto', 'Ensino fundamental incompleto'), ('fundamental_completo', 'Ensino fundamental completo'), ('medio_incompleto', 'Ensino Médio incompleto'), ('medio_completo', 'Ensino Médio completo'), ('tecnica_incompleta', 'Educação Técnica incompleta'), ('tecnica_completa', 'Educação Técnica completa'), ('superior_incompleta', 'Educação Superior incompleta'), ('superior_completa', 'Educação Superior completa')], max_length=100, verbose_name='Highest Education Level'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(help_text='Formato: xx xxxxx-xxxx', max_length=13, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: xx xxxxx-xxxx', regex='^\\d{2}\\s\\d{5}-\\d{4}$')], verbose_name='Phone Number'),
        ),
    ]
