# Generated by Django 5.2.7 on 2025-10-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_alter_candidate_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='disability',
            field=models.CharField(blank=True, choices=[('sem_deficiencia', 'Sem deficiência'), ('fisica', 'Física'), ('auditiva', 'Auditiva'), ('visual', 'Visual'), ('mental', 'Mental'), ('multipla', 'Múltipla'), ('reabilitado', 'Reabilitado')], default='', max_length=50, verbose_name='Possui deficiência? (PCD)'),
        ),
    ]
