# Generated by Django 5.2.7 on 2025-10-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_candidate_disability'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('prefiro_nao_informar', 'Prefiro não informar')], default='', max_length=30, verbose_name='Sexo'),
        ),
    ]
