# Generated by Django 5.2.7 on 2025-10-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='has_own_transportation',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=10, verbose_name='Possui transporte próprio?'),
        ),
    ]
