# Generated by Django 5.2.7 on 2025-10-17 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_alter_candidate_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='highest_education',
        ),
        migrations.AddField(
            model_name='candidate',
            name='has_relatives_in_company',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=10, verbose_name='Possui parentes ou amigos na empresa?'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='how_found_vacancy',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('indicacao_colaborador', 'Indicação de colaborador'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('sine', 'Sine'), ('outros', 'Outros')], default='', max_length=100, verbose_name='Como ficou sabendo da vaga?'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='how_found_vacancy_other',
            field=models.CharField(blank=True, help_text='Especifique se selecionou "Outros"', max_length=200, verbose_name='Outros - Especificar'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Nome da pessoa que indicou', max_length=200, verbose_name='Indicado Por'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='worked_at_pinte_before',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=10, verbose_name='Já trabalhou na Pinte Pinturas antes?'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cpf',
            field=models.CharField(help_text='Formato: xxx.xxx.xxx-xx', max_length=14, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: xxx.xxx.xxx-xx', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF'),
        ),
    ]
