# Generated by Django 5.2.7 on 2025-10-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_remove_candidate_field_of_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo ocupado na empresa', max_length=200, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='data_desligamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Desligamento'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='descricao_atividades',
            field=models.TextField(blank=True, help_text='Descreva as principais atividades realizadas', verbose_name='Descrição das Atividades'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='empresa',
            field=models.CharField(blank=True, help_text='Nome da empresa onde trabalhou', max_length=200, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='motivo_saida',
            field=models.TextField(blank=True, help_text='Explique o motivo da saída da empresa', verbose_name='Motivo da saída'),
        ),
    ]
