# Generated by Django 5.2.7 on 2025-10-17 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_candidate_cargo_candidate_data_admissao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='data_desligamento',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='descricao_atividades',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='motivo_saida',
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(help_text='Nome da empresa onde trabalhou', max_length=200, verbose_name='Empresa')),
                ('cargo', models.CharField(help_text='Cargo ocupado na empresa', max_length=200, verbose_name='Cargo')),
                ('descricao_atividades', models.TextField(blank=True, help_text='Descreva as principais atividades realizadas', verbose_name='Descrição das Atividades')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('data_desligamento', models.DateField(blank=True, null=True, verbose_name='Data de Desligamento')),
                ('motivo_saida', models.TextField(blank=True, help_text='Explique o motivo da saída da empresa', verbose_name='Motivo da saída')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_experiences', to='candidate.candidate', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'verbose_name_plural': 'Experiências Profissionais',
                'ordering': ['-data_desligamento', '-data_admissao'],
            },
        ),
    ]
