# Generated by Django 5.2.7 on 2025-10-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_remove_candidate_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('analfabeto', 'Analfabeto'), ('fundamental_incompleto', 'Ensino fundamental incompleto'), ('fundamental_completo', 'Ensino fundamental completo'), ('medio_incompleto', 'Ensino Médio incompleto'), ('medio_completo', 'Ensino Médio completo'), ('tecnica_incompleta', 'Educação Técnica incompleta'), ('tecnica_completa', 'Educação Técnica completa'), ('superior_incompleta', 'Educação Superior incompleta'), ('superior_completa', 'Educação Superior completa')], default='', max_length=100, verbose_name='Escolaridade'),
        ),
    ]
