# Generated by Django 5.2.7 on 2025-10-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_candidate_highest_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='availability_start',
            field=models.CharField(blank=True, choices=[('imediato', 'De imediato'), ('15_dias', '15 dias'), ('30_dias', '30 dias')], default='', max_length=20, verbose_name='Disponibilidade para início'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='currently_employed',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=10, verbose_name='Atualmente empregado'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='height_painting',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=100, verbose_name='Faz pintura em altura? Balancim/Cadeirinha/Andaimes'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='travel_availability',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=10, verbose_name='Disponibilidade para viagens'),
        ),
    ]
