# Generated by Django 5.2.7 on 2025-10-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_candidate_availability_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position_applied',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Position Applied For'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Years of Experience'),
        ),
    ]
