# Generated by Django 5.2.7 on 2025-10-20 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_alter_candidate_position_applied_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Entrevista Técnica - Desenvolvedor', max_length=200, verbose_name='Título da Entrevista')),
                ('interview_type', models.CharField(choices=[('phone', 'Telefone'), ('video', 'Vídeo'), ('in_person', 'Presencial'), ('technical', 'Técnica'), ('hr', 'RH')], default='video', max_length=20, verbose_name='Tipo de Entrevista')),
                ('scheduled_date', models.DateField(verbose_name='Data da Entrevista')),
                ('scheduled_time', models.TimeField(verbose_name='Horário da Entrevista')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duração estimada da entrevista em minutos', verbose_name='Duração (minutos)')),
                ('location', models.CharField(blank=True, help_text='Endereço físico ou link da reunião online', max_length=300, verbose_name='Local/Link')),
                ('description', models.TextField(blank=True, help_text='Detalhes adicionais sobre a entrevista', verbose_name='Descrição')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('rescheduled', 'Reagendada'), ('no_show', 'Candidato não compareceu')], default='scheduled', max_length=20, verbose_name='Status')),
                ('feedback', models.TextField(blank=True, help_text='Feedback do entrevistador após a entrevista', verbose_name='Feedback')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Avaliação de 1 a 5', null=True, verbose_name='Avaliação')),
                ('candidate_notified', models.BooleanField(default=False, verbose_name='Candidato Notificado')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Lembrete Enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidate.candidate', verbose_name='Candidato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Entrevistador')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
    ]
