# Generated by Django 5.2.7 on 2025-10-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_add_shortlisted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='whatsapp_message_sid',
            field=models.CharField(blank=True, help_text='ID da mensagem para rastreamento', max_length=100, verbose_name='WhatsApp Message SID'),
        ),
        migrations.AddField(
            model_name='interview',
            name='whatsapp_sent',
            field=models.BooleanField(default=False, help_text='Indica se a notificação via WhatsApp foi enviada', verbose_name='WhatsApp Enviado'),
        ),
        migrations.AddField(
            model_name='interview',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora do envio da notificação via WhatsApp', null=True, verbose_name='WhatsApp Enviado em'),
        ),
    ]
