# Generated by Django 5.2.7 on 2025-10-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_add_whatsapp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='Verified WhatsApp phone format (auto-detected)', max_length=20, verbose_name='WhatsApp Phone'),
        ),
    ]
