# Generated by Django 5.2.7 on 2025-10-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_add_whatsapp_phone_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Objective score based on multiple criteria (0-100)', max_digits=5, verbose_name='Candidate Score'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of score by category', verbose_name='Score Breakdown'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='score_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the score was last calculated', null=True, verbose_name='Score Last Updated'),
        ),
    ]
