# Generated by Django 5.2.7 on 2025-10-23 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0020_candidate_score_candidate_score_breakdown_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.IntegerField(default=27, help_text='Pontos máximos para anos de experiência', verbose_name='Anos de Experiência')),
                ('idle_time', models.IntegerField(default=5, help_text='Pontos máximos para tempo parado (desemprego)', verbose_name='Tempo Parado')),
                ('education_level', models.IntegerField(default=16, help_text='Pontos máximos para nível educacional', verbose_name='Nível Educacional')),
                ('courses', models.IntegerField(default=0, help_text='Pontos máximos para cursos adicionais', verbose_name='Cursos Adicionais')),
                ('skills', models.IntegerField(default=2, help_text='Pontos máximos para habilidades listadas', verbose_name='Habilidades')),
                ('certifications', models.IntegerField(default=0, help_text='Pontos máximos para certificações', verbose_name='Certificações')),
                ('immediate_availability', models.IntegerField(default=5, help_text='Pontos máximos para disponibilidade imediata', verbose_name='Disponibilidade Imediata')),
                ('own_transportation', models.IntegerField(default=5, help_text='Pontos máximos para transporte próprio', verbose_name='Transporte Próprio')),
                ('travel_availability', models.IntegerField(default=5, help_text='Pontos máximos para disponibilidade de viagens', verbose_name='Disponibilidade para Viagens')),
                ('height_painting', models.IntegerField(default=5, help_text='Pontos máximos para pintura em altura', verbose_name='Pintura em Altura')),
                ('average_rating', models.IntegerField(default=30, help_text='Pontos máximos para avaliação média de entrevistas', verbose_name='Avaliação Média')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se esta é a configuração ativa', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Configuração de Pontuação',
                'verbose_name_plural': 'Configurações de Pontuação',
                'ordering': ['-created_at'],
            },
        ),
    ]
