# Generated by Django 5.2.7 on 2025-10-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0021_add_scoring_weight_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringweight',
            name='worked_at_pinte_before',
            field=models.IntegerField(default=0, help_text='Pontos máximos para experiência prévia na empresa', verbose_name='Trabalhou na Pinte Antes'),
        ),
    ]
