# Generated by Django 5.2.7 on 2025-10-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_add_worked_at_pinte_before_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringweight',
            name='has_relatives_in_company',
            field=models.IntegerField(default=0, help_text='Pontos máximos para ter parentes ou amigos na empresa', verbose_name='Parentes/Amigos na Empresa'),
        ),
        migrations.AddField(
            model_name='scoringweight',
            name='referred_by',
            field=models.IntegerField(default=0, help_text='Pontos máximos para ser indicado por alguém', verbose_name='Indicado Por'),
        ),
    ]
