# Generated by Django 5.2.7 on 2025-10-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0023_add_referral_scoring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_photos/', verbose_name='Foto do Candidato'),
        ),
    ]
