# Generated by Django 5.2.7 on 2025-10-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0024_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False, help_text='Candidate agreed to receive WhatsApp notifications', verbose_name='WhatsApp Opt-in'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='whatsapp_opt_in_date',
            field=models.DateTimeField(blank=True, help_text='When candidate opted in to WhatsApp notifications', null=True, verbose_name='WhatsApp Opt-in Date'),
        ),
    ]
