# Generated by Django 5.2.7 on 2025-10-29 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0025_candidate_whatsapp_opt_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('candidate_created', 'Candidato Criado'), ('candidate_updated', 'Candidato Atualizado'), ('status_changed', 'Status Alterado'), ('interview_scheduled', 'Entrevista Agendada'), ('interview_updated', 'Entrevista Atualizada'), ('interview_cancelled', 'Entrevista Cancelada'), ('interview_completed', 'Entrevista Concluída'), ('interview_rescheduled', 'Entrevista Reagendada'), ('score_updated', 'Pontuação Atualizada'), ('note_added', 'Nota Adicionada')], max_length=30, verbose_name='Tipo de Ação')),
                ('description', models.TextField(help_text='Descrição detalhada da ação realizada', verbose_name='Descrição')),
                ('old_value', models.TextField(blank=True, help_text='Valor antes da alteração', null=True, verbose_name='Valor Anterior')),
                ('new_value', models.TextField(blank=True, help_text='Valor após a alteração', null=True, verbose_name='Novo Valor')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='candidate.candidate', verbose_name='Candidato')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='candidate.interview', verbose_name='Entrevista')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividade',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='candidate_a_timesta_3b2392_idx'), models.Index(fields=['action_type'], name='candidate_a_action__c170dd_idx'), models.Index(fields=['candidate'], name='candidate_a_candida_5125dd_idx'), models.Index(fields=['user'], name='candidate_a_user_id_529bab_idx')],
            },
        ),
    ]
