# Generated by Django 5.2.7 on 2025-10-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0026_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
