# Generated by Django 5.2.7 on 2025-10-30 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0027_alter_activitylog_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='whatsapp_phone',
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_phone_number',
            field=models.CharField(blank=True, help_text='Formato: xx xxxxx-xxxx', max_length=13, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: xx xxxxx-xxxx', regex='^\\d{2}\\s\\d{5}-\\d{4}$')], verbose_name='Second Phone Number'),
        ),
    ]
