# Generated by Django 5.2.7 on 2025-10-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0028_remove_candidate_whatsapp_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Password Hash'),
        ),
    ]
