# Generated by Django 5.2.7 on 2025-10-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0029_candidate_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='empresa',
            field=models.CharField(blank=True, help_text='Nome da empresa onde trabalhou', max_length=200, verbose_name='Empresa'),
        ),
    ]
