# Generated by Django 5.2.7 on 2025-10-30 17:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0030_alter_professionalexperience_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='work_cards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'txt', 'rtf', 'odt', 'xls', 'xlsx'])], verbose_name='Arquivo da Carteira de Trabalho')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_cards', to='candidate.candidate', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Carteira de Trabalho',
                'verbose_name_plural': 'Carteiras de Trabalho',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
