# Generated by Django 5.2.7 on 2025-11-14 20:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0031_workcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_key', models.CharField(db_index=True, help_text='Job position this questionnaire is for (matches Candidate.position_applied)', max_length=200, verbose_name='Position Key')),
                ('title', models.CharField(help_text='Descriptive title for this questionnaire', max_length=255, verbose_name='Title')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for tracking changes', verbose_name='Version')),
                ('is_active', models.BooleanField(default=False, help_text='Only one template per position should be active at a time', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Questionnaire Template',
                'verbose_name_plural': 'Questionnaire Templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['position_key', 'is_active'], name='candidate_q_positio_6f977b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question to ask the candidate', verbose_name='Question Text')),
                ('question_type', models.CharField(choices=[('multi_select', 'Multiple Select'), ('single_select', 'Single Select')], default='multi_select', max_length=20, verbose_name='Question Type')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this question appears', verbose_name='Display Order')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, help_text='Points awarded for correct answer', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points')),
                ('scoring_mode', models.CharField(choices=[('all_or_nothing', 'All or Nothing'), ('partial', 'Partial Credit')], default='all_or_nothing', help_text='How to score this question', max_length=20, verbose_name='Scoring Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='candidate.questionnairetemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CandidateQuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_key', models.CharField(db_index=True, help_text='Denormalized position key for easier querying', max_length=200, verbose_name='Position Key')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, help_text='Total score achieved', max_digits=7, verbose_name='Score')),
                ('max_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum possible score', max_digits=7, verbose_name='Maximum Score')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='candidate.candidate', verbose_name='Candidate')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='candidate.questionnairetemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Candidate Questionnaire Response',
                'verbose_name_plural': 'Candidate Questionnaire Responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(help_text='The text for this option', max_length=500, verbose_name='Option Text')),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this is a correct answer', verbose_name='Is Correct')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this option appears', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='candidate.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSelectedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='candidate.candidatequestionnaireresponse', verbose_name='Response')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_selections', to='candidate.question', verbose_name='Question')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_selections', to='candidate.questionoption', verbose_name='Option')),
            ],
            options={
                'verbose_name': 'Candidate Selected Option',
                'verbose_name_plural': 'Candidate Selected Options',
            },
        ),
        migrations.AddIndex(
            model_name='candidatequestionnaireresponse',
            index=models.Index(fields=['candidate', 'template'], name='candidate_c_candida_408277_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatequestionnaireresponse',
            index=models.Index(fields=['position_key', 'submitted_at'], name='candidate_c_positio_c2ab2c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateselectedoption',
            index=models.Index(fields=['response', 'question'], name='candidate_c_respons_d72a25_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateselectedoption',
            index=models.Index(fields=['option'], name='candidate_c_option__3f167a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateselectedoption',
            unique_together={('response', 'question', 'option')},
        ),
    ]
