# Generated by Django 5.2.7 on 2025-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0032_questionnairetemplate_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnairetemplate',
            options={'ordering': ['position_key', 'step_number', '-created_at'], 'verbose_name': 'Questionnaire Template', 'verbose_name_plural': 'Questionnaire Templates'},
        ),
        migrations.AddField(
            model_name='questionnairetemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description shown to candidates', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='questionnairetemplate',
            name='step_number',
            field=models.PositiveIntegerField(default=1, help_text='Order of this questionnaire in the multi-step form (1 = first step after basic info)', verbose_name='Step Number'),
        ),
        migrations.AddIndex(
            model_name='questionnairetemplate',
            index=models.Index(fields=['position_key', 'step_number'], name='candidate_q_positio_68fd3b_idx'),
        ),
    ]
