# Generated by Django 5.2.7 on 2025-11-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0033_add_step_number_to_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairetemplate',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this template is active (multiple templates can be active per position)', verbose_name='Is Active'),
        ),
    ]
