# Generated by Django 5.2.7 on 2025-11-18 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0034_update_questionnaire_is_active_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='option_points',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Used for Partial scoring in multi-select: relative points of this correct option', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Option Points'),
        ),
    ]
