# Generated by Django 5.2.7 on 2025-11-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0035_questionoption_option_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='scoring_mode',
            field=models.CharField(choices=[('all_or_nothing', 'All or Nothing'), ('partial', 'Partial Credit'), ('weighted', 'Weighted (by option points)')], default='all_or_nothing', help_text='How to score this question', max_length=20, verbose_name='Scoring Mode'),
        ),
    ]
