# Generated by Django 5.2.7 on 2025-11-28 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0036_add_weighted_scoring_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='candidate_name',
            field=models.CharField(blank=True, help_text='Nome do candidato no momento da ação', max_length=200, null=True, verbose_name='Nome do Candidato'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='candidate.candidate', verbose_name='Candidato'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='candidate.interview', verbose_name='Entrevista'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete Form'), ('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('shortlisted', 'Selected for Interview'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Application Status'),
        ),
    ]
