# Generated by Django 5.2.7 on 2025-11-28 17:26

from django.db import migrations


def populate_candidate_names(apps, schema_editor):
    """Populate candidate_name field for existing activity logs."""
    ActivityLog = apps.get_model('candidate', 'ActivityLog')
    
    # Update all activity logs that have a candidate but no candidate_name
    for log in ActivityLog.objects.filter(candidate__isnull=False, candidate_name__isnull=True):
        log.candidate_name = log.candidate.full_name
        log.save(update_fields=['candidate_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0037_preserve_activity_logs'),
    ]

    operations = [
        migrations.RunPython(populate_candidate_names, migrations.RunPython.noop),
    ]
