# Generated by Django 5.2.7 on 2026-02-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0038_populate_candidate_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='worked_at_pinte_before',
            field=models.CharField(
                max_length=10,
                verbose_name='Já trabalhou na empressa antes?',
                choices=[('sim', 'Sim'), ('nao', 'Não')],
                blank=True,
                default='',
            ),
        ),
    ]
