# Generated by Django 5.2.7 on 2026-02-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0038_populate_candidate_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='First Seen')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Last Seen')),
                ('visit_count', models.PositiveIntegerField(default=1, verbose_name='Visit Count')),
            ],
            options={
                'verbose_name': 'Demo User',
                'verbose_name_plural': 'Demo Users',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AlterField(
            model_name='candidate',
            name='worked_at_pinte_before',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=10, verbose_name='Já trabalhou na empressa antes?'),
        ),
    ]
